version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory:  ~/RobotFramework
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
#      - run: sudo pip install webdriverdownloader
      - run: wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
      - run: unzip chromedriver_linux64.zip
      - run: sudo mv chromedriver /usr/bin/chromedriver
      - run: sudo chown root:root /usr/bin/chromedriver
      - run: sudo chmod +x /usr/bin/chromedriver
      - run: robot -d results  Central/Launch.robot