version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory:  ~/RobotFramework
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
#      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
      - run: tar -xvzf geckodriver*
      - run: sudo mv geckodriver /usr/bin/geckodriver
      - run: sudo chown root:root /usr/bin/geckodriver
      - run: sudo chmod +x /usr/bin/geckodriver
#      - run: sudo apt-get install chromium-browser
      - run: robot -d results  Central/Launch.robot