version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory:  ~/RobotFramework
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run: brew install geckodriver
      - run: robot -d results  Central/Launch.robot